name: 'Build'

on:
  push:
    branches:
      - 'main'

jobs:
  reg-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch Marp
        run: >
          wget https://github.com/marp-team/marp-cli/releases/download/v2.5.0/marp-cli-v2.5.0-linux.tar.gz
          tar -vxzf marp-cli-v2.5.0-linux.tar.gz
          sudo mv marp /usr/local/bin
          rm marp-cli-v2.5.0-linux.tar.gz

      - name: Fetch Build Dependencies
        run: sudo apt-get install -y make

      - name: Build
        run: make build

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: preesntation.pdf
          path: build/presentation.pdf
