name: 'Build'

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cached Marp
        id: cached-marp
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/marp
          key: ${{ runner.os }}-primes

      - name: Fetch Marp
        if: steps.cached-marp.outputs.cache-hit != 'true'
        run: >
          wget https://github.com/marp-team/marp-cli/releases/download/v2.5.0/marp-cli-v2.5.0-linux.tar.gz && \
          tar -vxzf marp-cli-v2.5.0-linux.tar.gz && \
          sudo mv marp /usr/local/bin && \
          rm marp-cli-v2.5.0-linux.tar.gz

      - name: Fetch Build Dependencies
        run: sudo apt-get install -y make

      - name: Build
        run: make build

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Presentation
          path: build/presentation.pdf
